/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    BlogCard: typeof import('./components/blog/BlogCard.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    NavBar: typeof import('./components/layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBpx: typeof import('./components/common/SearchBpx.vue')['default']
    SideBar: typeof import('./components/layout/SideBar.vue')['default']
    TopBar: typeof import('./components/layout/TopBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
